#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.JobKits.Dashboard
{
    using System;
    using System.Collections.Generic;
    
    #line 2 "..\..\Dashboard\StandbyPage.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 3 "..\..\Dashboard\StandbyPage.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Dashboard\StandbyPage.cshtml"
    using Hangfire.JobKits;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Dashboard\StandbyPage.cshtml"
    using Hangfire.JobKits.Dashboard.Controls;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Dashboard\StandbyPage.cshtml"
    using Hangfire.JobKits.Dashboard.Controls.InputBox;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Dashboard\StandbyPage.cshtml"
    using Hangfire.JobKits.Resources;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Dashboard\StandbyPage.cshtml"
    using Hangfire.JobKits.Worker;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class StandbyPage : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");









WriteLiteral("\r\n");


            
            #line 11 "..\..\Dashboard\StandbyPage.cshtml"
  
    string selectedCategory = this.SelectedCategory;
    StandbyMap jobMap = this.Map;
    JobKitOptions options = this.Options;
    Layout = new LayoutPage(Strings.Standby_Title);
    var availableJobs = jobMap.JobCollection.Where(x => x.Value.CategoryName == selectedCategory).Select(x => x.Value).ToArray();


            
            #line default
            #line hidden
WriteLiteral("\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"");


            
            #line 19 "..\..\Dashboard\StandbyPage.cshtml"
                                        Write(Url.To(JobKitRoute.Standby.CssUrl));

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n<script type=\"text/javascript\">\r\n    var launchUrl = \'");


            
            #line 21 "..\..\Dashboard\StandbyPage.cshtml"
                Write(Url.To(JobKitRoute.Standby.LaunchUrl));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n    var recurringUrl = \'");


            
            #line 22 "..\..\Dashboard\StandbyPage.cshtml"
                   Write(Url.To(JobKitRoute.Standby.LaunchRecurringUrl));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n    var idFieldName = \'");


            
            #line 23 "..\..\Dashboard\StandbyPage.cshtml"
                  Write(StandbyKey.IdField);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n    var jobLinkBaseUrl = \'");


            
            #line 24 "..\..\Dashboard\StandbyPage.cshtml"
                     Write(Url.JobDetails(""));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n    var requireConfirmation = ");


            
            #line 25 "..\..\Dashboard\StandbyPage.cshtml"
                         Write(options.RequireConfirmation.ToString().ToLowerInvariant());

            
            #line default
            #line hidden
WriteLiteral(";\r\n    var messageLaunch = {\r\n        confirm: \'");


            
            #line 27 "..\..\Dashboard\StandbyPage.cshtml"
             Write(Strings.Standby_Launch);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n        confirmRecurring: \'");


            
            #line 28 "..\..\Dashboard\StandbyPage.cshtml"
                      Write(Strings.Standby_LaunchRecurring);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n        success: \'");


            
            #line 29 "..\..\Dashboard\StandbyPage.cshtml"
             Write(Strings.Standby_Success);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n        successRecurring: \'");


            
            #line 30 "..\..\Dashboard\StandbyPage.cshtml"
                      Write(Strings.Standby_SuccessRecurring);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n        failure: \'");


            
            #line 31 "..\..\Dashboard\StandbyPage.cshtml"
             Write(Strings.Standby_Failure);

            
            #line default
            #line hidden
WriteLiteral("\'\r\n    };\r\n</script>\r\n<script type=\"text/javascript\" src=\"");


            
            #line 34 "..\..\Dashboard\StandbyPage.cshtml"
                               Write(Url.To(JobKitRoute.Standby.JsUrl));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n\r\n    <div class=\"row\">\r\n        <div class=\"col-md-3\">\r\n           " +
" ");


            
            #line 38 "..\..\Dashboard\StandbyPage.cshtml"
       Write(SidebarControl.Render(Html, selectedCategory, jobMap));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div class=\"col-md-9\">\r\n            <h1 class=\"page-hea" +
"der\">");


            
            #line 41 "..\..\Dashboard\StandbyPage.cshtml"
                               Write(selectedCategory);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n");


            
            #line 42 "..\..\Dashboard\StandbyPage.cshtml"
             foreach (var job in availableJobs)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div class=\"panel panel-default\">\r\n                    <div class" +
"=\"panel-heading\">\r\n                        <div class=\"row\" onclick=\"onCollapse(" +
"this, \'");


            
            #line 46 "..\..\Dashboard\StandbyPage.cshtml"
                                                               Write(job.Id);

            
            #line default
            #line hidden
WriteLiteral("\');\">\r\n                            <div class=\"col-sm-10\">\r\n                     " +
"           <h4>\r\n                                    ");


            
            #line 49 "..\..\Dashboard\StandbyPage.cshtml"
                               Write(job.ActionName);

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 50 "..\..\Dashboard\StandbyPage.cshtml"
                                     if (!string.IsNullOrEmpty(job.Name))
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <span class=\"subtitle\">");


            
            #line 52 "..\..\Dashboard\StandbyPage.cshtml"
                                                          Write(job.Name);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");


            
            #line 53 "..\..\Dashboard\StandbyPage.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </h4>\r\n                            </div>\r\n      " +
"                      <div class=\"col-sm-2 text-right\">\r\n                       " +
"         <span class=\"btn glyphicon ");


            
            #line 57 "..\..\Dashboard\StandbyPage.cshtml"
                                                       Write(options.AlwaysCollapsed ? "glyphicon-chevron-up" : "glyphicon-chevron-down");

            
            #line default
            #line hidden
WriteLiteral("\" aria-hidden=\"true\"></span>\r\n                            </div>\r\n               " +
"         </div>\r\n                        \r\n                    </div>\r\n         " +
"           <div class=\"panel-body ");


            
            #line 62 "..\..\Dashboard\StandbyPage.cshtml"
                                       Write(options.AlwaysCollapsed ? "" : "hide");

            
            #line default
            #line hidden
WriteLiteral("\" id=\"");


            
            #line 62 "..\..\Dashboard\StandbyPage.cshtml"
                                                                                    Write(job.Id);

            
            #line default
            #line hidden
WriteLiteral("-body\">\r\n");


            
            #line 63 "..\..\Dashboard\StandbyPage.cshtml"
                         if (!string.IsNullOrWhiteSpace(job.Description))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <p>");


            
            #line 65 "..\..\Dashboard\StandbyPage.cshtml"
                          Write(job.Description);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");


            
            #line 66 "..\..\Dashboard\StandbyPage.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                            <form id=\"");


            
            #line 67 "..\..\Dashboard\StandbyPage.cshtml"
                                 Write(job.Id);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n");


            
            #line 68 "..\..\Dashboard\StandbyPage.cshtml"
                                 foreach (var parameter in job.Method.GetParameters())
                                {
                                    var control = InputControl.CreateControl(parameter, job);
                                    if (control is NullControl) { continue; }


            
            #line default
            #line hidden
WriteLiteral("                                    <div class=\"form-group\">\r\n                   " +
"                     ");


            
            #line 74 "..\..\Dashboard\StandbyPage.cshtml"
                                   Write(Html.RenderPartial(control));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </div>\r\n");


            
            #line 76 "..\..\Dashboard\StandbyPage.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                                <button type=\"button\" class=\"btn btn-primary\" onc" +
"lick=\"onEnqueue(this, \'");


            
            #line 77 "..\..\Dashboard\StandbyPage.cshtml"
                                                                                                   Write(job.Id);

            
            #line default
            #line hidden
WriteLiteral("\');return false;\">");


            
            #line 77 "..\..\Dashboard\StandbyPage.cshtml"
                                                                                                                             Write(Strings.Button_Created);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");


            
            #line 78 "..\..\Dashboard\StandbyPage.cshtml"
                                 if (!string.IsNullOrEmpty(job.RecurringJobId))
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <span class=\"cron-input\">\r\n                  " +
"                      <input type=\"text\" name=\"recurring_cron\" class=\"form-contr" +
"ol\" placeholder=\"Cron\" value=\"");


            
            #line 81 "..\..\Dashboard\StandbyPage.cshtml"
                                                                                                                           Write(job.RecurringJobCron);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                        <button class=\"btn btn-outline-succes" +
"s\" type=\"button\" onclick=\"onRecurring(this, \'");


            
            #line 82 "..\..\Dashboard\StandbyPage.cshtml"
                                                                                                                     Write(job.Id);

            
            #line default
            #line hidden
WriteLiteral("\');return false;\">");


            
            #line 82 "..\..\Dashboard\StandbyPage.cshtml"
                                                                                                                                               Write(Strings.Button_Recurring);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                                        \r\n                            " +
"        </span>\r\n");


            
            #line 85 "..\..\Dashboard\StandbyPage.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </form>\r\n                        <div id=\"");


            
            #line 87 "..\..\Dashboard\StandbyPage.cshtml"
                            Write(job.Id);

            
            #line default
            #line hidden
WriteLiteral("-alerts\" class=\"panel-alerts\"></div>\r\n                    </div>\r\n               " +
" </div>\r\n");


            
            #line 90 "..\..\Dashboard\StandbyPage.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n");


        }
    }
}
#pragma warning restore 1591
