//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.JobKits.Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hangfire.JobKits.Dashboard.Contents.resx.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Enqueue 的當地語系化字串。
        /// </summary>
        public static string Button_Created {
            get {
                return ResourceManager.GetString("Button_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Recurring 的當地語系化字串。
        /// </summary>
        public static string Button_Recurring {
            get {
                return ResourceManager.GetString("Button_Recurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fields are missing: 的當地語系化字串。
        /// </summary>
        public static string Field_Missing {
            get {
                return ResourceManager.GetString("Field_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Action 的當地語系化字串。
        /// </summary>
        public static string MonitorPage_Table_Action {
            get {
                return ResourceManager.GetString("MonitorPage_Table_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cron 的當地語系化字串。
        /// </summary>
        public static string MonitorPage_Table_Cron {
            get {
                return ResourceManager.GetString("MonitorPage_Table_Cron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Executed Time 的當地語系化字串。
        /// </summary>
        public static string MonitorPage_Table_ExecutedTime {
            get {
                return ResourceManager.GetString("MonitorPage_Table_ExecutedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Name 的當地語系化字串。
        /// </summary>
        public static string MonitorPage_Table_Name {
            get {
                return ResourceManager.GetString("MonitorPage_Table_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Scheduled Time 的當地語系化字串。
        /// </summary>
        public static string MonitorPage_Table_ScheduleTime {
            get {
                return ResourceManager.GetString("MonitorPage_Table_ScheduleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Status 的當地語系化字串。
        /// </summary>
        public static string MonitorPage_Table_Status {
            get {
                return ResourceManager.GetString("MonitorPage_Table_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Job Monitor 的當地語系化字串。
        /// </summary>
        public static string MonitorPage_Title {
            get {
                return ResourceManager.GetString("MonitorPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed 的當地語系化字串。
        /// </summary>
        public static string MonitorStatus_Failed {
            get {
                return ResourceManager.GetString("MonitorStatus_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invalid 的當地語系化字串。
        /// </summary>
        public static string MonitorStatus_Invalid {
            get {
                return ResourceManager.GetString("MonitorStatus_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Successed 的當地語系化字串。
        /// </summary>
        public static string MonitorStatus_Successed {
            get {
                return ResourceManager.GetString("MonitorStatus_Successed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unexecuted 的當地語系化字串。
        /// </summary>
        public static string MonitorStatus_Unexecuted {
            get {
                return ResourceManager.GetString("MonitorStatus_Unexecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unstarted 的當地語系化字串。
        /// </summary>
        public static string MonitorStatus_Unstarted {
            get {
                return ResourceManager.GetString("MonitorStatus_Unstarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Daily 的當地語系化字串。
        /// </summary>
        public static string Range_Daily {
            get {
                return ResourceManager.GetString("Range_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Monthly 的當地語系化字串。
        /// </summary>
        public static string Range_Monthly {
            get {
                return ResourceManager.GetString("Range_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Weekly 的當地語系化字串。
        /// </summary>
        public static string Range_Weekly {
            get {
                return ResourceManager.GetString("Range_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 An error occured during launching:  的當地語系化字串。
        /// </summary>
        public static string Standby_Failure {
            get {
                return ResourceManager.GetString("Standby_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Launch Job ? 的當地語系化字串。
        /// </summary>
        public static string Standby_Launch {
            get {
                return ResourceManager.GetString("Standby_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Launch Recurring Job ? 的當地語系化字串。
        /// </summary>
        public static string Standby_LaunchRecurring {
            get {
                return ResourceManager.GetString("Standby_LaunchRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No standby jobs found. 的當地語系化字串。
        /// </summary>
        public static string Standby_NoJobs {
            get {
                return ResourceManager.GetString("Standby_NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Job launched with id:  的當地語系化字串。
        /// </summary>
        public static string Standby_Success {
            get {
                return ResourceManager.GetString("Standby_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Recurring Job launched  的當地語系化字串。
        /// </summary>
        public static string Standby_SuccessRecurring {
            get {
                return ResourceManager.GetString("Standby_SuccessRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Standby Jobs 的當地語系化字串。
        /// </summary>
        public static string Standby_Title {
            get {
                return ResourceManager.GetString("Standby_Title", resourceCulture);
            }
        }
    }
}
